// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nctjzmecqswokyeztier.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdGp6bWVjcXN3b2t5ZXp0aWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTE5MzQsImV4cCI6MjA2MDQ4NzkzNH0.9NcwYDNfwXwigDsJzddoUthl2ZUKNkkd4ukXRAwd2kM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);